export const FETCH = {
  ENTITY: {
    START: 'FETCH_ENTITY_START',
    SUCCESS: 'FETCH_ENTITY_SUCCESS',
    ERROR: 'FETCH_ENTITY_ERROR',
  },
  SHOPPING_LIST: {
    START: 'FETCH_SHOPPING_LIST_START',
    SUCCESS: 'FETCH_SHOPPING_LIST_SUCCESS',
    ERROR: 'FETCH_SHOPPING_LIST_ERROR',
  }
};
export const STORAGE = {
  CREATE_PRODUCT: {
    START: 'STORAGE_CREATE_PRODUCT_START',
    SUCCESS: 'STORAGE_CREATE_PRODUCT_SUCCESS',
    ERROR: 'STORAGE_CREATE_PRODUCT_ERROR',
  },
  UPDATE_PRODUCT: {
    START: 'STORAGE_UPDATE_PRODUCT_START',
    SUCCESS: 'STORAGE_UPDATE_PRODUCT_SUCCESS',
    ERROR: 'STORAGE_UPDATE_PRODUCT_ERROR',
  },
}
