export const FETCH = {
  SHOPPINGS: {
    START: 'FETCH_SHOPPINGS_START',
    SUCCESS: 'FETCH_SHOPPINGS_SUCCESS',
    ERROR: 'FETCH_SHOPPINGS_ERROR',
  }
};
export const STORAGE = {
  CREATE_PRODUCT: {
    START: 'STORAGE_CREATE_PRODUCT_START',
    SUCCESS: 'STORAGE_CREATE_PRODUCT_SUCCESS',
    ERROR: 'STORAGE_CREATE_PRODUCT_ERROR',
  },
  UPDATE_PRODUCT: {
    START: 'STORAGE_UPDATE_PRODUCT_START',
    SUCCESS: 'STORAGE_UPDATE_PRODUCT_SUCCESS',
    ERROR: 'STORAGE_UPDATE_PRODUCT_ERROR',
  },
  SET_SHOPPINGS: 'STORAGE_SET_SHOPPINGS',
}
export const DRAWER = {
  RIGHT: 'DRAWER_RIGHT',
  LEFT: 'DRAWER_LEFT',
}
